version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn helpcenter.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/helpcenter-be/static/
      - media_volume:/helpcenter-be/media/
    expose:
      - 8000
    env_file:
      - ./env/django/.env.dev
    depends_on:
      - global_db
      - articles_db
      - guides_db
      - ideas_db

  global_db:
    image: postgres:12.0-alpine
    volumes:
      - global_db_volume:/var/lib/postgresql/data/
    env_file:
      - ./env/db/global_db.env
      
  articles_db:
    image: postgres:12.0-alpine
    volumes:
      - articles_db_volume:/var/lib/postgresql/data/
    env_file:
      - ./env/db/articles_db.env

  guides_db:
    image: postgres:12.0-alpine
    volumes:
      - guides_db_volume:/var/lib/postgresql/data/
    env_file:
      - ./env/db/guides_db.env

  ideas_db:
    image: postgres:12.0-alpine
    volumes:
      - ideas_db_volume:/var/lib/postgresql/data/
    env_file:
      - ./env/db/ideas_db.env

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/helpcenter-be/static/
      - media_volume:/helpcenter-be/media/
    ports:
      - 8000:80
    depends_on:
      - web
    
volumes:
  global_db_volume:
  articles_db_volume:
  guides_db_volume:
  ideas_db_volume:
  static_volume:
  media_volume:
